version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: ivannabrovchuk1/lab4-examples:compose-django
    container_name: django
    networks:
      - publ
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.site
    image: ivannabrovchuk1/lab4-examples:compose-monitoring
    container_name: monitoring
    depends_on:
      - django
    network_mode: host
    volumes:
      - ./../lab5/server.log:/app/server.log

volumes:
  monit-log:
    driver: local

networks:
  publ:
    driver: bridge